### ISSUE TITLE
data pre-processed

### ISSUE THREAD

**Issue by ClaireZTH** [SajadMo/ECG-Heartbeat-Classification-seq2seq-model#1]
Could you upload the code of data pre-process? I want to know how to pre-process.Thank you!

**Comment by MousaviSajad** [comment]
Dear ClaireZTH,
I have uploaded the code for data pre-processing. You can follow the instructions of the readme file in the "data preprocessing_Matlab" folder to download the MIT-BIH database and perform data pre-processing. Then, put the pre-processed datasets into the "data" folder!
Sajad

**Comment by ClaireZTH** [comment]
Dear Sajad：   Thank you very much！it helps me a lot。 ClaireZTH------------------ 原始邮件 ------------------
发件人: "Sajad Mousavi"<notifications@github.com>
发送时间: 2019年4月23日(星期二) 凌晨1:17
收件人: "SajadMo/ECG-Heartbeat-Classification-seq2seq-model"<ECG-Heartbeat-Classification-seq2seq-model@noreply.github.com>;
抄送: "ClaireZTH"<2695961972@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [SajadMo/ECG-Heartbeat-Classification-seq2seq-model] datapre-processed (#1)



Dear ClaireZTH,
 I have uploaded the code for data pre-processing. You can follow the instructions of the readme file in the "data preprocessing_Matlab" folder to download the MIT-BIH database and perform data pre-processing. Then, put the pre-processed datasets into the "data" folder!
 Sajad
 
&mdash;
