### ISSUE TITLE
Tensorflow version ?

### ISSUE THREAD

**Issue by mlaprise** [SajadMo/ECG-Heartbeat-Classification-seq2seq-model#5]
Hi, we're trying to replicate the result of the paper. Could you tell us which version of tensorflow you used  for the training ?

**Comment by MousaviSajad** [comment]
Hi,

Thank you for your interest. The version of TensorFlow was 1.14 or 1.15.

Regards,
Sajad

**Comment by mlaprise** [comment]
Thx !
